version: '2.1'

services:
  alfresco:
    environment:
      - INDEX=solr6

  solr:
    image: docker.io/xenit/alfresco-solr6:1.4
    container_name: solr
    volumes:
      - solr:/opt/alfresco/alf_data
    environment:
      - ALFRESCO_HOST=alfresco
      - JAVA_XMS=512M
      - JAVA_XMX=2048M
      - SHARDING=false

volumes:
  solr: