version: '2.1'

services:
  alfresco:
    environment:
    - INDEX=solr4

  solr:
    image: xenit/alfresco-solr4:5.1
    volumes:
    - solr:/opt/alfresco/alf_data
    environment:
    - ALFRESCO_HOST=alfresco

volumes:
  solr: