version: '2.1'

services:
  alfresco:
    image: ${ALFRESCO_IMAGE:-docker.io/xenit/alfresco-zipkin-repo:local}
    volumes:
    - alfresco:/opt/alfresco/alf_data
    - ./alfresco/netcat-healthcheck.sh:/netcat-healthcheck.sh:z
    - logs:/usr/local/tomcat/logs
    ports:
    - ${COMPOSE_ALFRESCO_TCP_8080:-8081:8080}
    environment:
    - DB_URL=${COMPOSE_DB_URL:-jdbc:postgresql://database:5432/alfresco}
    - SOLR_HOST=solr
    - INDEX=noindex
    - SOLR_SSL=none
    - ENABLE_CLUSTERING=true
    - DYNAMIC_SHARD_REGISTRATION=true
    - GLOBAL_local.transform.service.enabled=false
    - DEBUG=true
    depends_on:
    - database
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/alfresco/s/api/server"]
      interval: 10s
      timeout: 3s
      retries: 3

  database:
    image: docker.io/xenit/postgres:10.10
    volumes:
    - postgres:/var/lib/postgresql/data
    environment:
    - POSTGRES_USER=alfresco
    - POSTGRES_PASSWORD=admin
    - POSTGRES_DB=alfresco

  shard1:
    image: hub.xenit.eu/alfresco-enterprise/alfresco-solr6:1.3.0.6
    container_name: shard1
    ports:
      - 8081:8080
    hostname: shard1
    environment:
      - JAVA_XMX=1024M
      - SOLR_HOST=shard1
      - ALFRESCO_SSL=none
      - CORES_TO_TRACK=alfresco
      - CORES_ALFRESCO=shard1
      - GLOBAL_ALL_shard.method=DB_ID
      - GLOBAL_ALL_shard.count=2
      - GLOBAL_shard1_shard.instance=0

  shard2:
    image: hub.xenit.eu/alfresco-enterprise/alfresco-solr6:1.3.0.6
    container_name: shard2
    ports:
      - 8082:8080
    hostname: shard2
    environment:
      - JAVA_XMX=1024M
      - SOLR_HOST=shard2
      - ALFRESCO_SSL=none
      - CORES_TO_TRACK=alfresco
      - CORES_ALFRESCO=shard2
      - GLOBAL_ALL_shard.method=DB_ID
      - GLOBAL_ALL_shard.count=2
      - GLOBAL_shard2_shard.instance=1

volumes:
  alfresco:
  postgres:
  logs:
