name: 'Continuous Integration'
on: [push, pull_request]

env:
  ORG_GRADLE_PROJECT_alfresco_nexus_username: ${{ secrets.ALFRESCO_NEXUS_USERNAME }}
  ORG_GRADLE_PROJECT_alfresco_nexus_password: ${{ secrets.ALFRESCO_NEXUS_PASSWORD }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Check
        run: ./gradlew check
      - name: Test
        run: ./gradlew test
      - name: Integration tests
        run: ./gradlew integrationTests
      #      - name: Upload analysis to sonarcloud
      #        env:
      #          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      #          GITHUB_TOKEN: ${{ github.token }}
      #        run: ./gradlew sonarqube -Dsonar.projectKey=xenit-eu_alfresco-gradle-sdk -Dsonar.organization=xenit-eu -Dsonar.host.url=https://sonarcloud.io
      - name: Publish
        if: ${{ github.ref == 'refs/heads/master' || startswith(github.ref, 'refs/tags/') }}
        env:
          ORG_GRADLE_PROJECT_signingKey: ${{ secrets.MAVEN_CENTRAL_GPG_KEY }}
          ORG_GRADLE_PROJECT_signingPassword: ${{ secrets.MAVEN_CENTRAL_GPG_PASSWORD }}
          ORG_GRADLE_PROJECT_sonatype_username: ${{ secrets.MAVEN_CENTRAL_USERNAME }}
          ORG_GRADLE_PROJECT_sonatype_password: ${{ secrets.MAVEN_CENTRAL_PASSWORD }}
        run: ./gradlew publish